### ISSUE TITLE
Vertex_graph

### ISSUE THREAD

**Issue by Zhzet9611** [VanshDhar/Hair_Shape_Deformation_based_on_AutoHair#1]
great work!
would you mind to tell me how can i convert a hairstyle mesh(stored as obj or ply) in to vertex_graph which you used in your code?

**Comment by VanshDhar** [comment]
You need to store all the vertices in a map as a key and then all the vertices, each vertex is connected to will become its value, then using that information you can calculate the other information and store it accordingly as mentioned in the code

**Comment by Zhzet9611** [comment]
> You need to store all the vertices in a map as a key and then all the vertices, each vertex is connected to will become its value, then using that information you can calculate the other information and store it accordingly as mentioned in the code

**Comment by Zhzet9611** [comment]
Thanks a lot ! In the last month,i archieve this function on your basis , but the dataset i use is just USC SALON (343 hairstyle encoded in strands) , for some short hair ,the result is not satisfied.
